# Generated by Django 5.0 on 2025-09-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Make your profile visible to recruiters'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_contact_info',
            field=models.BooleanField(default=True, help_text='Show contact information to recruiters'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_education',
            field=models.BooleanField(default=True, help_text='Show education to recruiters'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_experience',
            field=models.BooleanField(default=True, help_text='Show work experience to recruiters'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_links',
            field=models.BooleanField(default=True, help_text='Show links to recruiters'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_skills',
            field=models.BooleanField(default=True, help_text='Show skills to recruiters'),
        ),
    ]
