# Generated by Django 5.0 on 2025-10-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_is_public_profile_show_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commute_radius',
            field=models.IntegerField(default=25, help_text='Preferred commute radius in miles'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_location_address',
            field=models.CharField(blank=True, help_text='Address of preferred location', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of preferred location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of preferred location', max_digits=9, null=True),
        ),
    ]
