# Generated by Django 5.0 on 2025-09-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
    ]
