# Generated by Django 5.0 on 2025-11-22 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_applicationemail_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCandidateSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name for this search', max_length=200)),
                ('skills', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('experience', models.CharField(blank=True, max_length=500)),
                ('search_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('search_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_radius', models.CharField(blank=True, max_length=10)),
                ('sort_by', models.CharField(default='skills_match', max_length=20)),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Get notified when new candidates match this search')),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Last time this search was checked for new matches', null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, help_text='Last time a notification was sent for this search', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_candidate_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saved Candidate Searches',
                'ordering': ['-updated_at'],
            },
        ),
    ]
