# Generated by Django 5.0 on 2025-11-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_officelocation_city_officelocation_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
